spring:
  datasource:
    username: root
    password: '{cipher}AQBbIxPHR75W5PgWV8GrrPIr72dkSBxsQAytYlQLDzYCnh5FfNiHJPxrSGp8hzT1wFfbNZzkRD5Ain2H9Mdq93aREmLklB/BwzNiYoik8Blgi7b5jiR9fdbJaKt1+udJPSviVBtHpHShyU24pI4cfl7ToWm4KdR1UrofpPFgol16YskC6okNp7jeSy1Ska8g3gtyY7aOMKwufHp7fAR7j1AgLdezvvQ62+2Afu6nBSmtjZ79zA3/gL44a/yjt4ABGvMxJp1VEA79SwDQ7/tKlm9kw0r4G2BE+iEyqC/kjFbw2c4Qx8Cxtf0Yo3w2Dii6u6LGRXZYJw9BAglcBxt95mra3FPsktFgz/SzBmw9nSqcKW5YAOM8jhTUcuDCALmnYJ0='
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
gateway:
  ip: 172.28.144.1